# Global defaults
default_repo: 'TimeWarpEngineering/timewarp-architecture'
default_branch: 'master'

# Sync schedule
schedule:
  cron: '0 9 * * 1'  # Every Monday at 9:00 AM UTC

# Repository-specific configurations
repos:
  - repo: 'TimeWarpEngineering/timewarp-architecture'
    branch: 'master'
    path_transform:
      remove_prefix: 'TimeWarp.Architecture/'  # Auto-remove prefix from dest paths
    files:
      # Kanban task management structure - sync from central location
      - source_path: 'TimeWarp.Architecture/Kanban/Overview.md'
      - source_path: 'TimeWarp.Architecture/Kanban/Task-Template.md'
      - source_path: 'TimeWarp.Architecture/Kanban/Backlog/Overview.md'
      - source_path: 'TimeWarp.Architecture/Kanban/ToDo/Overview.md'
      - source_path: 'TimeWarp.Architecture/Kanban/InProgress/Overview.md'
      - source_path: 'TimeWarp.Architecture/Kanban/Done/Overview.md'
      - source_path: 'TimeWarp.Architecture/Kanban/Backlog/Scratch/Overview.md'
      
      # COMMENTED OUT - Using Kanban instead
      # - source_path: 'TimeWarp.Architecture/.gitignore'
      # - source_path: 'TimeWarp.Architecture/.editorconfig'
      # - source_path: 'TimeWarp.Architecture/.ai/'
      # - source_path: 'TimeWarp.Architecture/Directory.Build.props'
      #   dest_path: 'Directory.Build.props.template'

# Global sync options
sync_options:
  default_dest_to_source: true  # Auto-default dest_path to source_path
  overwrite_existing: true
  ignore_missing: false

# Files to exclude globally
exclude_files:
  - '.github/sync-config.yml'
  - '.github/workflows/'  # Don't sync workflows automatically
  - 'Kanban/Backlog/*.md'  # Don't overwrite our specific backlog tasks
  - 'Kanban/ToDo/*.md'     # Don't overwrite our specific todo tasks
  - 'Kanban/InProgress/*.md' # Don't overwrite our specific in-progress tasks
  - 'Kanban/Done/*.md'     # Don't overwrite our specific done tasks